language: node_js
sudo: false
matrix:
  include:
    - node_js: "10"
    - node_js: "11"
    - node_js: "12"
    - node_js: "13"
    - node_js: "14"
  fast_finish: true
script:
  - "npm install"
  - "npm run eslint"
  - "npm run test"
after_script: "npm run coverage"
